org: noaoh
app: spotify-currently-listening
service: spotify-currently-listening
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  environment:
    SPOTIFY_CLIENT_ID: ${param:spotify-client-id}
    SPOTIFY_CLIENT_SECRET: ${param:spotify-client-secret}
    SPOTIFY_REFRESH_TOKEN: ${param:spotify-refresh-token}
    LOCAL_URL: ${param:local-url}
    GITHUB_URL: ${param:github-url}

functions:
  currentlyListening:
    handler: handler.currentlyListening
    events:
      - httpApi:
          path: /currently-listening
          method: get
